glossary_codes = ['XXGVTXX – Requiring a defence under POCA (consent) if the value of the suspected money laundering falls below a value of £3,000',
'XXPRFXX – Professional enablers: persons providing professional services or specialist knowledge that wittingly or unwittingly facilitates money laundering.',
'XXTBMLXX – Trade-based money laundering (TBML)',
'XXPROPXX – Purchase, sale and rental of real estate property',
'XXVAXX - Virtual assets',
'XXMLTMXX – Money laundering through markets',
'XXSNEXX – Money laundering linked to sanctioned entities',
'XXSATXX – HMRC Self-Assessment Tax Refund system',
'XXGPSXX – Government Priority Schemes',
'XXCVDXX – General code',
'XXTEOSXX - Tax evasion offshore',
'XXTEUKXX - Tax evasion UK-based',
'XXF1XX - Proceeds from benefit fraud',
'XXF2XX - Excise evasion (duty on alcohol, tobacco, fuel etc.)',
'XXF3XX - Corporate tax evasion (tax evasion by businesses, corporations)',
'XXF4XX - Personal tax evasion (tax evasion by individuals e.g. income tax)',
'XXF5XX - VAT fraud e.g. carousel, Missing Trader Intra-Community (MTIC) fraud',
'XXF9XX - Frauds against private sector',
'XXD9XX - Bribery and corruption',
'XXV2XX – Risk to vulnerable adults',
'XXV3XX – Risk to children – particularly including sexual abuse and exploitation',
'XXD9XX – Bribery and corruption',
'XXILTXX – Illegal lotteries',
'XXFIREXX – Firearms',
'XXDRUXX – Illegal supply of drugs',
'XXOICXX – Organised immigration crime',
'XXMSHTXX – Modern slavery/human trafficking',
'XXPCPXX - Counter-proliferation',
'XXVICTXX - Where the purpose of the activity is to return money to a victim of crime']